---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=8.2.2"
license_file: LICENSE
name: ios
namespace: cisco
description: Ansible Network Collection for Cisco IOS devices.
readme: README.md
repository: https://github.com/ansible-collections/cisco.ios
issues: https://github.com/ansible-collections/cisco.ios/issues
tags: [cisco, ios, iosxe, networking]
build_ignore:
  - .yamllint
  - .prettierignore
  - .pre-commit-config.yaml
  - .isort.cfg
  - .gitignore
  - .darglint
  - .flake8
  - .ansible-lint
  - sonar-project.properties
  - codecov.yml
  - .github/
version: "11.2.0"
