---
authors:
  - Ansible Network Community (ansible-network)
license_file: LICENSE
name: ios
namespace: cisco
readme: README.rst
repository: https://github.com/ansible-network/ansible_collections.cisco.ios
