---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=6.1.0"
license_file: LICENSE
name: ios
namespace: cisco
description: Ansible Network Collection for Cisco IOS devices.
readme: README.md
repository: https://github.com/ansible-collections/cisco.ios
issues: https://github.com/ansible-collections/cisco.ios/issues
tags: [cisco, ios, iosxe, networking]
version: "9.0.3"
