---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
license_file: LICENSE
name: ios
namespace: cisco
readme: README.rst
repository: https://github.com/ansible-collections/cisco.ios
tags: [cisco, ios, iosxe, networking]
