# -*- coding: utf-8 -*-
# Copyright 2020 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the cisco.ios_bgp_af module
"""


class Bgp_afArgs(object):  # pylint: disable=R0903
    """The arg spec for the cisco.ios_bgp_af module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        "config": {
            "type": "dict",
            "options": {
                "asn": {"type": "str", "required": True},
                "afi": {
                    "type": "str",
                    "choices": [
                        "ipv4",
                        "ipv6",
                        "l2vpn",
                        "nsap",
                        "rtfilter",
                        "vpnv4",
                        "vpnv6",
                    ],
                },
                "af_modifier": {
                    "type": "str",
                    "choices": ["flowspec", "mdt", "multicast", "mvpn", "unicast"],
                },
                "vrf": {"type": "str"},
                "aggregate_address": {
                    "type": "dict",
                    "options": {
                        "address": {"type": "str"},
                        "netmask": {"type": "str"},
                        "advertise_map": {"type": "str"},
                        "as_confed_set": {"type": "bool"},
                        "as_set": {"type": "bool"},
                        "attribute_map": {"type": "str"},
                        "summary_only": {"type": "bool"},
                        "suppress_map": {"type": "str"},
                    },
                    "default": {
                        "description": "Set a command to its defaults",
                        "type": "bool",
                    },
                },
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "type": "str",
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "parsed",
                "rendered",
            ],
            "default": "merged",
        },
    }  # pylint: disable=C0301
