# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the ios_snmp_server module
"""


class Snmp_serverArgs(object):  # pylint: disable=R0903
    """The arg spec for the ios_snmp_server module
    """

    argument_spec = {
        "config": {
            "options": {
                "accounting": {
                    "options": {
                        "command": {"type": "str"},
                        "command_default": {"type": "bool"},
                        "disable_community": {"type": "str"},
                        "disable_user": {"type": "str"},
                    },
                    "type": "dict",
                },
                "cache": {"type": "int"},
                "chassis_id": {"type": "str"},
                "communities": {
                    "elements": "dict",
                    "options": {
                        "acl_v4": {"type": "str"},
                        "acl_v6": {"type": "str"},
                        "name": {"type": "str"},
                        "ro": {"type": "bool"},
                        "rw": {"type": "bool"},
                        "view": {"type": "str"},
                    },
                    "type": "list",
                },
                "contact": {"type": "str"},
                "context": {"elements": "str", "type": "list"},
                "drop": {
                    "options": {
                        "unknown_user": {"type": "bool"},
                        "vrf_traffic": {"type": "bool"},
                    },
                    "type": "dict",
                },
                "engine_id": {
                    "options": {
                        "local": {"type": "str"},
                        "remote": {
                            "options": {
                                "host": {"type": "str"},
                                "id": {"type": "str"},
                                "udp_port": {"type": "int"},
                                "vrf": {"type": "str"},
                            },
                            "type": "dict",
                        },
                    },
                    "type": "dict",
                },
                "file_transfer": {
                    "options": {"access_group": {"type": "str"}},
                    "type": "dict",
                },
                "groups": {
                    "elements": "dict",
                    "options": {
                        "context": {"type": "str"},
                        "group": {"type": "str"},
                        "notify": {"type": "str"},
                        "read": {"type": "str"},
                        "version": {"choices": ["v1", "v3", "v2c"], "type": "str"},
                        "write": {"type": "str"},
                    },
                    "type": "list",
                },
                "hosts": {
                    "elements": "dict",
                    "options": {
                        "host": {"type": "str"},
                        "informs": {"type": "bool"},
                        "traps": {"type": "bool"},
                        "version": {"choices": ["1", "2c", "3"], "type": "str"},
                        "vrf": {"type": "str"},
                    },
                    "type": "list",
                },
                "if_index": {"type": "bool"},
                "inform": {
                    "options": {
                        "pending": {"type": "int"},
                        "retries": {"type": "int"},
                        "timeout": {"type": "int"},
                    },
                    "type": "dict",
                },
                "ip": {
                    "options": {
                        "dscp": {"type": "int"},
                        "precedence": {"type": "int"},
                    },
                    "type": "dict",
                },
                "location": {"type": "str"},
                "manager": {"type": "int"},
                "packet_size": {"type": "int"},
                "password_policy": {
                    "elements": "dict",
                    "options": {
                        "change": {"type": "int"},
                        "digits": {"type": "int"},
                        "lower_case": {"type": "int"},
                        "max_len": {"type": "int"},
                        "min_len": {"type": "int"},
                        "policy_name": {"type": "str"},
                        "special_char": {"type": "int"},
                        "upper_case": {"type": "int"},
                        "username": {"type": "str"},
                    },
                    "type": "list",
                },
                "queue_length": {"type": "int"},
                "source_interface": {
                    "type": "dict",
                    "options": {
                        "informs": {"type": "bool"},
                        "traps": {"type": "bool"},
                        "interface": {"type": "str"},
                    },
                },
                "system_shutdown": {"type": "bool"},
                "trap_source": {"type": "str"},
                "trap_timeout": {"type": "int"},
                "traps": {
                    "options": {
                        "auth_framework": {
                            "options": {
                                "sec_violation": {"type": "bool"},
                                "state": {
                                    "choices": ["enable", "disable"],
                                    "type": "str",
                                },
                            },
                            "type": "dict",
                        },
                        "bfd": {
                            "options": {
                                "session_down": {"type": "bool"},
                                "session_up": {"type": "bool"},
                            },
                            "type": "dict",
                        },
                        "bgp": {
                            "options": {
                                "cbgp2": {"type": "bool"},
                                "state": {
                                    "choices": ["enable", "disable"],
                                    "type": "str",
                                },
                                "state_changes": {
                                    "options": {
                                        "all": {"type": "bool"},
                                        "backward-trans": {"type": "bool"},
                                        "limited": {"type": "bool"},
                                        "state": {
                                            "choices": ["enable", "disable"],
                                            "type": "str",
                                        },
                                    },
                                    "type": "dict",
                                },
                                "threshold": {
                                    "options": {
                                        "prefix": {"type": "bool"},
                                        "state": {
                                            "choices": ["enable", "disable"],
                                            "type": "str",
                                        },
                                    },
                                    "type": "dict",
                                },
                            },
                            "type": "dict",
                        },
                        "bridge": {
                            "options": {
                                "newroot": {"type": "bool"},
                                "state": {
                                    "choices": ["enable", "disable"],
                                    "type": "str",
                                },
                                "topologychange": {"type": "bool"},
                            },
                            "type": "dict",
                        },
                        "casa": {"type": "bool"},
                        "cef": {
                            "options": {
                                "inconsistency": {"type": "bool"},
                                "peer_fib_state_change": {"type": "bool"},
                                "peer_state_change": {"type": "bool"},
                                "resource_failure": {"type": "bool"},
                                "state": {
                                    "choices": ["enable", "disable"],
                                    "type": "str",
                                },
                            },
                            "type": "dict",
                        },
                        "cnpd": {"type": "bool"},
                        "config": {"type": "bool"},
                        "config_copy": {"type": "bool"},
                        "config_ctid": {"type": "bool"},
                        "cpu": {
                            "options": {
                                "state": {
                                    "choices": ["enable", "disable"],
                                    "type": "str",
                                },
                                "threshold": {"type": "bool"},
                            },
                            "type": "dict",
                        },
                        "dhcp": {"type": "bool"},
                        "dlsw": {
                            "options": {
                                "circuit": {"type": "bool"},
                                "state": {
                                    "choices": ["enable", "disable"],
                                    "type": "str",
                                },
                                "tconn": {"type": "bool"},
                            },
                            "type": "dict",
                        },
                        "eigrp": {"type": "bool"},
                        "entity": {"type": "bool"},
                        "ethernet": {
                            "options": {
                                "cfm": {
                                    "options": {
                                        "alarm": {"type": "bool"},
                                        "cc": {
                                            "options": {
                                                "config": {"type": "bool"},
                                                "cross_connect": {"type": "bool"},
                                                "loop": {"type": "bool"},
                                                "mep_down": {"type": "bool"},
                                                "mep_up": {"type": "bool"},
                                            },
                                            "type": "dict",
                                        },
                                        "crosscheck": {
                                            "options": {
                                                "mep-missing": {"type": "bool"},
                                                "mep-unknown": {"type": "bool"},
                                                "service-up": {"type": "bool"},
                                            },
                                            "type": "dict",
                                        },
                                    },
                                    "type": "dict",
                                },
                                "evc": {
                                    "options": {
                                        "create": {"type": "bool"},
                                        "delete": {"type": "bool"},
                                        "status": {"type": "bool"},
                                    },
                                    "type": "dict",
                                },
                            },
                            "type": "dict",
                        },
                        "event_manager": {"type": "bool"},
                        "flowmon": {"type": "bool"},
                        "firewall": {
                            "options": {
                                "state": {
                                    "choices": ["enable", "disable"],
                                    "type": "str",
                                },
                                "serverstatus": {"type": "bool"},
                            },
                            "type": "dict",
                        },
                        "frame_relay": {
                            "options": {
                                "state": {
                                    "choices": ["enable", "disable"],
                                    "type": "str",
                                },
                                "subif": {
                                    "options": {
                                        "count": {"type": "int"},
                                        "interval": {"type": "int"},
                                        "state": {
                                            "choices": ["enable", "disable"],
                                            "type": "str",
                                        },
                                    },
                                    "type": "dict",
                                },
                            },
                            "type": "dict",
                        },
                        "fru_ctrl": {"type": "bool"},
                        "hsrp": {"type": "bool"},
                        "ike": {
                            "options": {
                                "policy": {
                                    "options": {
                                        "add": {"type": "bool"},
                                        "delete": {"type": "bool"},
                                    },
                                    "type": "dict",
                                },
                                "tunnel": {
                                    "options": {
                                        "start": {"type": "bool"},
                                        "stop": {"type": "bool"},
                                    },
                                    "type": "dict",
                                },
                            },
                            "type": "dict",
                        },
                        "ipmulticast": {"type": "bool"},
                        "ipsec": {
                            "options": {
                                "cryptomap": {
                                    "options": {
                                        "add": {"type": "bool"},
                                        "attach": {"type": "bool"},
                                        "delete": {"type": "bool"},
                                        "detach": {"type": "bool"},
                                    },
                                    "type": "dict",
                                },
                                "too_many_sas": {"type": "bool"},
                                "tunnel": {
                                    "options": {
                                        "start": {"type": "bool"},
                                        "stop": {"type": "bool"},
                                    },
                                    "type": "dict",
                                },
                            },
                            "type": "dict",
                        },
                        "ipsla": {"type": "bool"},
                        "l2tun": {
                            "options": {
                                "pseudowire_status": {"type": "bool"},
                                "session": {"type": "bool"},
                            },
                            "type": "dict",
                        },
                        "msdp": {"type": "bool"},
                        "mvpn": {"type": "bool"},
                        "ospf": {
                            "options": {
                                "cisco_specific": {
                                    "options": {
                                        "error": {
                                            "options": {
                                                "config_error": {"type": "bool"},
                                                "shamlink": {"type": "bool"},
                                                "virt_config_error": {
                                                    "type": "bool"
                                                },
                                            },
                                            "type": "dict",
                                        },
                                        "lsa": {
                                            "options": {
                                                "lsa-maxage": {"type": "bool"},
                                                "lsa-originate": {"type": "bool"},
                                            },
                                            "type": "dict",
                                        },
                                        "retransmit": {
                                            "options": {
                                                "packets": {"type": "bool"},
                                                "shamlink": {"type": "bool"},
                                                "virt_packets": {"type": "bool"},
                                            },
                                            "type": "dict",
                                        },
                                        "state_change": {
                                            "options": {
                                                "nssa_trans_change": {
                                                    "type": "bool"
                                                },
                                                "shamlink": {
                                                    "options": {
                                                        "interface": {
                                                            "type": "bool"
                                                        },
                                                        "neighbor": {
                                                            "type": "bool"
                                                        },
                                                    },
                                                    "type": "dict",
                                                },
                                            },
                                            "type": "dict",
                                        },
                                    },
                                    "type": "dict",
                                },
                                "error": {
                                    "options": {
                                        "authentication_failure": {"type": "bool"},
                                        "bad_packet": {"type": "bool"},
                                        "config_error": {"type": "bool"},
                                        "virt_authentication_failure": {
                                            "type": "bool"
                                        },
                                        "virt_bad_packet": {"type": "bool"},
                                        "virt_config_error": {"type": "bool"},
                                    },
                                    "type": "dict",
                                },
                                "state": {
                                    "choices": ["enable", "disable"],
                                    "type": "str",
                                },
                                "state_change": {"type": "bool"},
                            },
                            "type": "dict",
                        },
                        "pim": {
                            "options": {
                                "invalid_pim_message": {"type": "bool"},
                                "neighbor_change": {"type": "bool"},
                                "rp_mapping_change": {"type": "bool"},
                                "state": {
                                    "choices": ["enable", "disable"],
                                    "type": "str",
                                },
                            },
                            "type": "dict",
                        },
                        "pki": {"type": "bool"},
                        "rsvp": {"type": "bool"},
                        "snmp": {
                            "options": {
                                "authentication": {"type": "bool"},
                                "coldstart": {"type": "bool"},
                                "linkdown": {"type": "bool"},
                                "linkup": {"type": "bool"},
                                "warmstart": {"type": "bool"},
                            },
                            "type": "dict",
                        },
                        "syslog": {"type": "bool"},
                        "transceiver_all": {"type": "bool"},
                        "tty": {"type": "bool"},
                        "vrrp": {"type": "bool"},
                    },
                    "type": "dict",
                },
                "users": {
                    "elements": "dict",
                    "options": {
                        "access": {"type": "str"},
                        "group": {"type": "str"},
                        "remote": {"type": "str"},
                        "udp_port": {"type": "int"},
                        "user": {"type": "str"},
                        "version": {"choices": ["v1", "v2c", "v3"], "type": "str"},
                        "vrf": {"type": "str"},
                    },
                    "type": "list",
                },
                "views": {
                    "elements": "dict",
                    "options": {
                        "excluded": {"type": "bool"},
                        "family_name": {"type": "str"},
                        "included": {"type": "bool"},
                        "name": {"type": "str"},
                    },
                    "type": "list",
                },
            },
            "type": "dict",
        },
        "running_config": {"type": "str"},
        "state": {
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "parsed",
                "gathered",
                "rendered",
            ],
            "default": "merged",
            "type": "str",
        },
    }  # pylint: disable=C0301
