# -*- coding: utf-8 -*-
# Copyright 2025 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function


__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# ansible.content_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the documentation in the module file and re-run
# ansible.content_builder commenting out
# the path to external 'docstring' in build.yaml.
#
##############################################

"""
The arg spec for the ios_bfd_templates module
"""


class Bfd_templatesArgs(object):  # pylint: disable=R0903
    """The arg spec for the ios_bfd_templates module"""

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "name": {"required": True, "type": "str"},
                "hop": {
                    "required": True,
                    "choices": ["single_hop", "multi_hop"],
                    "type": "str",
                },
                "interval": {
                    "required": False,
                    "type": "dict",
                    "options": {
                        "min_tx": {"required": True, "type": "int"},
                        "min_rx": {"required": True, "type": "int"},
                        "multiplier": {"required": True, "type": "int"},
                    },
                },
                "dampening": {
                    "required": False,
                    "type": "dict",
                    "options": {
                        "half_life_period": {"required": True, "type": "int"},
                        "reuse_threshold": {"required": True, "type": "int"},
                        "suppress_threshold": {"required": True, "type": "int"},
                        "max_suppress_time": {"required": True, "type": "int"},
                    },
                },
                "echo": {"required": False, "type": "bool"},
                "authentication": {
                    "required": False,
                    "type": "dict",
                    "options": {
                        "type": {
                            "required": False,
                            "choices": [
                                "sha_1",
                                "md5",
                                "keyed_sha_1",
                                "keyed_md5",
                                "meticulous_keyed_sha_1",
                                "meticulous_keyed_md5",
                            ],
                            "type": "str",
                        },
                        "keychain": {"required": False, "type": "str"},
                    },
                },
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "rendered",
                "gathered",
                "purged",
                "parsed",
            ],
            "default": "merged",
            "type": "str",
        },
    }  # pylint: disable=C0301
