---
devices:
  - platform: ios_acl_interfaces
    count: 1

  - scenario: ios-acl-interfaces-merged
    count: 1

  - scenario: ios-acl-interfaces-replaced
    count: 1

  - scenario: ios-acl-interfaces-overridden
    count: 1

  - scenario: ios-acl-interfaces-deleted
    count: 1

  - scenario: ios-acl-interfaces-rtt
    count: 1
