---
devices:
  - platform: ios_vrf_address_family
    count: 1

  - scenario: ios-vrf-af-merged
    count: 1

  - scenario: ios-vrf-af-deleted
    count: 1

  - platform: ios_vrf_address_family
    count: 2
