# -*- coding: utf-8 -*-
# Copyright 2025 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function


__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# ansible.content_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the documentation in the module file and re-run
# ansible.content_builder commenting out
# the path to external 'docstring' in build.yaml.
#
##############################################

"""
The arg spec for the ios_bfd_static module
"""


class Bfd_staticArgs(object):  # pylint: disable=R0903
    """The arg spec for the ios_bfd_static module"""

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "destination": {"type": "str", "required": True},
                "vrf": {"type": "str"},
                "next_hop": {"type": "str"},
                "interface": {"type": "str"},
                "source_vrf": {"type": "str"},
                "source_ip": {"type": "str"},
                "group_name": {"type": "str"},
                "passive": {"type": "bool", "default": False},
                "log": {"type": "bool", "default": False},
                "unassociate": {"type": "bool", "default": False},
            },
            "mutually_exclusive": [
                ["next_hop", "interface"],
                ["next_hop", "source_vrf"],
                ["next_hop", "source_ip"],
                ["interface", "source_vrf"],
                ["interface", "source_ip"],
            ],
            "required_together": [
                ["source_vrf", "source_ip"],
            ],
        },
        "state": {
            "type": "str",
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
    }  # pylint: disable=C0301
