---
all:
  children:
    cisshgo_targets:
      vars:
        ansible_host: 127.0.0.1
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_user: admin
        ansible_password: admin
        ansible_become: false
        ansible_network_cli_ssh_type: libssh
        ansible_libssh_key_exchange_algorithms: +diffie-hellman-group14-sha1,+diffie-hellman-group-exchange-sha1
        ansible_libssh_hostkeys: +ssh-rsa
        ansible_libssh_publickey_algorithms: +ssh-rsa
        ansible_command_timeout: 200
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      children:
        ios_gathered:
          hosts:
            cisshgo-ios-gathered:
              ansible_port: 10000
        ios_merged:
          hosts:
            cisshgo-ios-merged:
              ansible_port: 10001
        ios_replaced:
          hosts:
            cisshgo-ios-replaced:
              ansible_port: 10002
        ios_overridden:
          hosts:
            cisshgo-ios-overridden:
              ansible_port: 10003
        ios_deleted:
          hosts:
            cisshgo-ios-deleted:
              ansible_port: 10004
