# -*- coding: utf-8 -*-
# Copyright 2024 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# ansible.content_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the documentation in the module file and re-run
# ansible.content_builder commenting out
# the path to external 'docstring' in build.yaml.
#
##############################################

"""
The arg spec for the ios_vrf_address_family module
"""


class Vrf_address_familyArgs(object):  # pylint: disable=R0903
    """The arg spec for the ios_vrf_address_family module
    """

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "name": {"type": "str", "required": True},
                "address_families": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "afi": {"type": "str", "choices": ["ipv4", "ipv6"]},
                        "safi": {
                            "type": "str",
                            "choices": ["multicast", "unicast"],
                        },
                        "bgp": {
                            "type": "dict",
                            "options": {
                                "next_hop": {
                                    "type": "dict",
                                    "options": {"loopback": {"type": "int"}},
                                }
                            },
                        },
                        "export": {
                            "type": "dict",
                            "options": {
                                "map": {"type": "str"},
                                "ipv4": {
                                    "type": "dict",
                                    "options": {
                                        "multicast": {
                                            "type": "dict",
                                            "options": {
                                                "prefix": {"type": "int"},
                                                "map": {"type": "str"},
                                            },
                                        },
                                        "unicast": {
                                            "type": "dict",
                                            "options": {
                                                "prefix": {"type": "int"},
                                                "map": {"type": "str"},
                                                "allow_evpn": {"type": "bool"},
                                            },
                                        },
                                    },
                                },
                            },
                        },
                        "import_config": {
                            "type": "dict",
                            "options": {
                                "map": {"type": "str"},
                                "ipv4": {
                                    "type": "dict",
                                    "options": {
                                        "multicast": {
                                            "type": "dict",
                                            "options": {
                                                "prefix": {"type": "int"},
                                                "map": {"type": "str"},
                                            },
                                        },
                                        "unicast": {
                                            "type": "dict",
                                            "options": {
                                                "limit": {"type": "int"},
                                                "map": {"type": "str"},
                                                "allow_evpn": {"type": "bool"},
                                            },
                                        },
                                    },
                                },
                            },
                        },
                        "maximum": {
                            "type": "dict",
                            "options": {
                                "routes": {
                                    "type": "dict",
                                    "options": {
                                        "limit": {"type": "int"},
                                        "threshold": {"type": "int"},
                                        "reinstall": {
                                            "type": "dict",
                                            "options": {
                                                "threshold": {"type": "int"}
                                            },
                                        },
                                        "warning_only": {"type": "bool"},
                                    },
                                }
                            },
                        },
                        "inter_as_hybrid": {
                            "type": "dict",
                            "options": {
                                "csc": {
                                    "type": "dict",
                                    "options": {"next_hop": {"type": "str"}},
                                },
                                "next_hop": {"type": "str"},
                            },
                        },
                    },
                },
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "choices": [
                "parsed",
                "gathered",
                "deleted",
                "merged",
                "replaced",
                "rendered",
                "overridden",
            ],
            "default": "merged",
            "type": "str",
        },
    }  # pylint: disable=C0301
