# -*- coding: utf-8 -*-
# Copyright 2020 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the cisco.ios_bgp_global module
"""


class Bgp_globalArgs(object):
    """The arg spec for the cisco.ios_bgp_global module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        "config": {
            "type": "dict",
            "options": {
                "asn": {"type": "str", "required": True},
                "bgp": {
                    "type": "dict",
                    "options": {
                        "always_compare_med": {"type": "bool"},
                        "asnotation": {"type": "bool"},
                        "bestpath": {
                            "type": "dict",
                            "options": {
                                "aigp": {"type": "bool"},
                                "compare_routerid": {"type": "bool"},
                                "cost_community": {"type": "bool"},
                                "med": {
                                    "type": "dict",
                                    "options": {
                                        "confed": {"type": "bool"},
                                        "missing_as_worst": {"type": "bool"},
                                    },
                                },
                            },
                        },
                        "client_to_client": {
                            "type": "dict",
                            "options": {
                                "all": {"type": "bool"},
                                "intra_cluster": {"type": "bool"},
                            },
                        },
                        "cluster_id": {"type": "bool"},
                        "confederation": {
                            "type": "dict",
                            "options": {
                                "identifier": {"type": "str"},
                                "peers": {"type": "str"},
                            },
                        },
                        "consistency_checker": {
                            "type": "dict",
                            "options": {
                                "auto_repair": {
                                    "type": "dict",
                                    "options": {
                                        "enable": {"type": "bool"},
                                        "interval": {"type": "int"},
                                    },
                                },
                                "error_message": {
                                    "type": "dict",
                                    "options": {
                                        "enable": {"type": "bool"},
                                        "interval": {"type": "int"},
                                    },
                                },
                            },
                        },
                        "deterministic_med": {"type": "bool"},
                        "dmzlink_bw": {"type": "bool"},
                        "enforce_first_as": {"type": "bool"},
                        "enhanced_error": {"type": "bool"},
                        "fast_external_fallover": {"type": "bool"},
                        "graceful_restart": {
                            "type": "dict",
                            "options": {
                                "set": {"type": "bool"},
                                "extended": {"type": "bool"},
                                "restart_time": {"type": "int"},
                                "stalepath_time": {"type": "int"},
                            },
                        },
                        "graceful_shutdown": {
                            "type": "dict",
                            "options": {
                                "community": {"type": "str"},
                                "local_preference": {"type": "int"},
                            },
                        },
                        "inject_map": {
                            "type": "dict",
                            "options": {
                                "name": {"type": "str"},
                                "exist_map_name": {"type": "str"},
                                "copy_attributes": {"type": "bool"},
                            },
                        },
                        "listen": {
                            "type": "dict",
                            "options": {
                                "limit": {"type": "int"},
                                "range": {
                                    "type": "dict",
                                    "options": {
                                        "v4address_with_subnet": {
                                            "type": "str"
                                        },
                                        "v6address_with_subnet": {
                                            "type": "str"
                                        },
                                        "peer_group": {"type": "str"},
                                    },
                                },
                            },
                        },
                        "log_neighbor_changes": {"type": "bool"},
                        "maxas_limit": {"type": "int"},
                        "maxcommunity_limit": {"type": "int"},
                        "maxextcommunity_limit": {"type": "int"},
                        "nopeerup_delay": {
                            "type": "dict",
                            "options": {
                                "cold_boot": {"type": "int"},
                                "nsf_switchover": {"type": "int"},
                                "post_boot": {"type": "int"},
                                "user_initiated": {"type": "int"},
                            },
                        },
                        "refresh": {
                            "type": "dict",
                            "options": {
                                "max_eor_time": {"type": "int"},
                                "stalepath_time": {"type": "int"},
                            },
                        },
                        "regexp": {"type": "bool"},
                        "router_id": {
                            "type": "dict",
                            "options": {
                                "address": {"type": "str"},
                                "interface": {"type": "str"},
                                "vrf": {"type": "str"},
                            },
                        },
                        "scan_time": {"type": "int"},
                        "snmp": {"type": "bool"},
                        "sso": {"type": "bool"},
                        "suppress_inactive": {"type": "bool"},
                        "transport": {"type": "bool"},
                        "update_delay": {"type": "bool"},
                        "update_group": {"type": "bool"},
                    },
                },
                "bmp": {
                    "type": "dict",
                    "options": {
                        "buffer_size": {"type": "int"},
                        "initial_refresh": {
                            "type": "dict",
                            "options": {
                                "delay": {"type": "int"},
                                "skip": {"type": "bool"},
                            },
                        },
                        "server": {"type": "int"},
                    },
                },
                "neighbor": {
                    "type": "dict",
                    "options": {
                        "address": {"type": "str"},
                        "tag": {"type": "str"},
                        "ipv6_adddress": {"type": "str"},
                        "bmp_activate": {
                            "type": "dict",
                            "options": {
                                "all": {"type": "bool"},
                                "server": {"type": "int"},
                            },
                        },
                        "cluster_id": {"type": "str"},
                        "description": {"type": "str"},
                        "disable_connected_check": {"type": "bool"},
                        "ebgp_multihop": {
                            "type": "dict",
                            "options": {
                                "enable": {"type": "bool"},
                                "hop_count": {"type": "int"},
                            },
                        },
                        "fall_over": {
                            "type": "dict",
                            "options": {
                                "bfd": {
                                    "type": "dict",
                                    "options": {
                                        "set": {"type": "bool"},
                                        "multi_hop": {"type": "bool"},
                                        "single_hop": {"type": "bool"},
                                    },
                                },
                                "route_map": {"type": "str"},
                            },
                        },
                        "ha_mode": {
                            "type": "dict",
                            "options": {
                                "set": {"type": "bool"},
                                "disable": {"type": "bool"},
                            },
                        },
                        "inherit": {"type": "str"},
                        "local_as": {
                            "type": "dict",
                            "options": {
                                "set": {"type": "bool"},
                                "number": {"type": "int"},
                            },
                        },
                        "log_neighbor_changes": {
                            "type": "dict",
                            "options": {
                                "set": {"type": "bool"},
                                "disable": {"type": "bool"},
                            },
                        },
                        "password": {"type": "str"},
                        "path_attribute": {
                            "type": "dict",
                            "options": {
                                "discard": {
                                    "type": "dict",
                                    "options": {
                                        "type": {"type": "int"},
                                        "range": {
                                            "type": "dict",
                                            "options": {
                                                "start": {"type": "int"},
                                                "end": {"type": "int"},
                                            },
                                        },
                                        "in": {"type": "bool"},
                                    },
                                },
                                "treat_as_withdraw": {
                                    "type": "dict",
                                    "options": {
                                        "type": {"type": "int"},
                                        "range": {
                                            "type": "dict",
                                            "options": {
                                                "start": {"type": "int"},
                                                "end": {"type": "int"},
                                            },
                                        },
                                        "in": {"type": "bool"},
                                    },
                                },
                            },
                        },
                        "peer_group": {"type": "str"},
                        "remote_as": {"type": "int"},
                        "shutdown": {
                            "type": "dict",
                            "options": {
                                "set": {"type": "bool"},
                                "graceful": {"type": "int"},
                            },
                        },
                        "timers": {
                            "type": "dict",
                            "options": {
                                "interval": {"type": "int"},
                                "holdtime": {"type": "int"},
                                "min_holdtime": {"type": "int"},
                            },
                        },
                        "transport": {
                            "type": "dict",
                            "options": {
                                "connection_mode": {
                                    "type": "dict",
                                    "options": {
                                        "active": {"type": "bool"},
                                        "passive": {"type": "bool"},
                                    },
                                },
                                "multi_session": {"type": "bool"},
                                "path_mtu_discovery": {
                                    "type": "dict",
                                    "options": {
                                        "set": {"type": "bool"},
                                        "disable": {"type": "bool"},
                                    },
                                },
                            },
                        },
                        "ttl_security": {"type": "int"},
                        "version": {"type": "int"},
                    },
                },
                "route_server_context": {
                    "type": "dict",
                    "options": {
                        "name": {"type": "str"},
                        "address_family": {
                            "type": "dict",
                            "options": {
                                "afi": {
                                    "type": "str",
                                    "choices": ["ipv4", "ipv6"],
                                },
                                "modifier": {
                                    "type": "str",
                                    "choices": ["multicast", "unicast"],
                                },
                                "import_map": {"type": "str"},
                            },
                        },
                        "description": {"type": "str"},
                    },
                },
                "scope": {
                    "type": "dict",
                    "options": {
                        "global": {"type": "bool"},
                        "vrf": {"type": "str"},
                    },
                },
                "template": {
                    "type": "dict",
                    "options": {
                        "peer_policy": {"type": "str"},
                        "peer_session": {"type": "str"},
                    },
                },
                "timers": {
                    "type": "dict",
                    "options": {
                        "keepalive": {"type": "int"},
                        "holdtime": {"type": "int"},
                        "min_holdtime": {"type": "int"},
                    },
                },
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "type": "str",
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "parsed",
                "rendered",
            ],
            "default": "merged",
        },
    }
