---
name: "Close Old Issues & PRs ⌛️"

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  close_stale_items:
    uses: ansible/ansible-content-actions/.github/workflows/close_stale_issues_pr.yml@main
